[package]
name = "paper_setup"
version = "0.1.0"
edition = "2021"

[dependencies]
octocrab = "0.18"
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.13"
regex = "1.5"
tokio = { version = "1", features = ["full"] }
